# Generated by Django 5.2.7 on 2025-11-09 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
