# Generated by Django 5.2.7 on 2025-11-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberacion', '0003_estudiante_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='boleta',
            field=models.FileField(blank=True, null=True, upload_to='boletas/'),
        ),
    ]
