# Generated by Django 5.2.8 on 2025-11-26 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberacion', '0004_estudiante_boleta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_liberacion',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='firmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nivel_ingles',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
